apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        error_log /var/log/nginx/error.log debug;
        access_log /var/log/nginx/access.log;

        upstream auth-service {
            server auth-service:5001;
        }

        upstream orders-service {
            server orders-service:5003;
        }

        server {
            listen 80;
            server_name localhost;

            location /debug {
                return 200 "Nginx is working! Request URI: $request_uri\n";
                add_header Content-Type text/plain;
            }

            location /health {
                return 200 'Nginx OK';
                add_header Content-Type text/plain;
            }

            location /api/products {
                proxy_pass http://products-service/api/products;
                proxy_set_header Host $host;
                proxy_set_header Cookie $http_cookie;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_pass_header Set-Cookie;
                proxy_cookie_path / /;
                proxy_cookie_domain ~.* "";
            }

            location /test-auth {
                proxy_pass http://auth-service/api/users;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Cookie $http_cookie;
                proxy_set_header Authorization $http_authorization; 
                proxy_connect_timeout 10s;
                proxy_read_timeout 10s;
                proxy_send_timeout 10s;
            }

            location /api/users {
                proxy_pass http://auth-service/api/users;
                proxy_set_header Cookie $http_cookie;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Authorization $http_authorization;
                proxy_pass_header Set-Cookie;
                proxy_cookie_domain ~.* "";
                proxy_cookie_path / /;
                proxy_connect_timeout 10s;
                proxy_read_timeout 10s;
                proxy_send_timeout 10s;
            }

            location /api/orders {
                proxy_pass http://orders-service/api/orders;
                proxy_set_header Cookie $http_cookie;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Authorization $http_authorization;
                proxy_pass_header Set-Cookie;
                proxy_cookie_path / /;
                proxy_cookie_domain ~.* "";
                proxy_connect_timeout 10s;
                proxy_read_timeout 10s;
                proxy_send_timeout 10s;
            }

            location ~ ^/api/auth {
                proxy_pass http://auth-service$request_uri;
                proxy_set_header Cookie $http_cookie;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Authorization $http_authorization;
                proxy_pass_header Set-Cookie;
                proxy_cookie_path / /;
                proxy_cookie_domain ~.* "";
                proxy_connect_timeout 10s;
                proxy_read_timeout 10s;
                proxy_send_timeout 10s;
            }

            location / {
                proxy_pass http://frontend/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_connect_timeout 10s;
                proxy_read_timeout 10s;
                proxy_send_timeout 10s;
            }
        }
    }