apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      initContainers:
      - name: prisma-migrate
        image: hani221b/proshop-auth-service:0.0.1
        command: ["npx", "prisma", "migrate", "deploy"]
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: POSTGRES_PASSWORD
      containers:
        - name: auth-service-cont
          image: hani221b/proshop-auth-service:0.0.1
          ports:
            - containerPort: 5001 
