apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: default
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6c3Ryb25ncGFzc3dvcmRAYXV0aC1kYjo1NDMyL2F1dGgtZGI/c2NoZW1hPXB1YmxpYw==