apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-cont
          image: hani221b/proshop-frontend:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 
