apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: products-db-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
  volumeName: products-db-pv
  storageClassName: ""