apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      initContainers:
      - name: prisma-migrate
        image: hani221b/proshop-products-service:0.0.1
        command: ["npx", "prisma", "migrate", "deploy"]
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: products-db-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: products-db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: products-db-secret
              key: POSTGRES_PASSWORD
      containers:
        - name: products-service-cont
          image: hani221b/proshop-products-service:0.0.1
          imagePullPolicy: Always
          env:  
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: products-service-secret
                key: DATABASE_URL
          ports: 
            - containerPort: 5002
