apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service-cont
          image: hani221b/proshop-orders-service:0.0.1
          imagePullPolicy: Always
          env:  
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: auth-orders-secret
                key: DATABASE_URL
          ports:
            - containerPort: 5003
