apiVersion: v1
kind: Secret
metadata:
  name: auth-orders-secret
  namespace: default
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6c3Ryb25ncGFzc3dvcmRAb3JkZXJzLWRiOjU0MzIvb3JkZXJzLWRiP3NjaGVtYT1wdWJsaWM=