apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: default
  labels:
    app: adminer
spec:
  selector:
    app: adminer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: NodePort  